news-job:
  next-execution:
    seconds: 120
  execution-interval:
    seconds: 60
  bing:
    subscription-id: 9b251e28ada24ce0b75762f869b19d3c
    max-records-fetch: 500

feign:
  client:
    config:
      default:
        loggerLevel: basic

spring:
  datasource:
    url: jdbc:h2:mem:mydb;MODE=PostgreSQL;
    username: sa
    password: password
    driverClassName: org.h2.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

remote:
  bing:
    base-url: https://api.bing.microsoft.com/v7.0/news/search