news-job:
  next-execution:
    minutes: 2
  execution-interval:
    minutes: 3
  bing:
    subscription-id: 9b251e28ada24ce0b75762f869b19d3c
    max-records-fetch: 500


spring:
  datasource:
    url: jdbc:sqlserver://stock-news.database.windows.net:1433;database=news-feed;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: news-feed@stock-news
    password: Stock_2023
    #driverClassName: microsoft.sqlserver.jdbc.SQLServerDriver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false
  h2:
    console.enabled: true

remote:
  bing:
    base-url: https://api.bing.microsoft.com/v7.0/news/search

logging:
  level:
    com:
      news:
        feed:
          newsfeed:
            remote:
              bing:
                MicrosoftBingClient: DEBUG
